cmake_minimum_required(VERSION 3.0)

# Set up solution dependency
set(FALCON_ENGINE_INCLUDE_DIR ${FALCON_ENGINE_ROOT_DIR}/include)
set(FALCON_ENGINE_LIBRARY_DIR ${FALCON_ENGINE_ROOT_DIR}/lib)

# Set up solution output
set(FALCON_ENGINE_ARCHIVE_OUTPUT_DIR ${FALCON_ENGINE_ROOT_DIR}/bin)
set(FALCON_ENGINE_LIBRARY_OUTPUT_DIR ${FALCON_ENGINE_ROOT_DIR}/bin)
set(FALCON_ENGINE_RUNTIME_OUTPUT_DIR ${FALCON_ENGINE_ROOT_DIR}/bin)

# Set up library type
set(FALCON_ENGINE_LIBRARY_TYPE "STATIC")

function(fe_set_target_output CURRENT_TARGET_NAME)

    assert_defined(FALCON_ENGINE_OUTPUT_SUFFIX)

    set_target_properties(${CURRENT_TARGET_NAME} PROPERTIES
        PROJECT_LABEL                           ${CURRENT_TARGET_NAME}

        ARCHIVE_OUTPUT_DIRECTORY 			    ${FALCON_ENGINE_ARCHIVE_OUTPUT_DIR}
        ARCHIVE_OUTPUT_DIRECTORY_DEBUG          ${FALCON_ENGINE_ARCHIVE_OUTPUT_DIR}/Debug
        ARCHIVE_OUTPUT_DIRECTORY_RELEASE        ${FALCON_ENGINE_ARCHIVE_OUTPUT_DIR}/Release
        ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${FALCON_ENGINE_ARCHIVE_OUTPUT_DIR}/Release
        ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL     ${FALCON_ENGINE_ARCHIVE_OUTPUT_DIR}/Release

        RUNTIME_OUTPUT_DIRECTORY 			    ${FALCON_ENGINE_RUNTIME_OUTPUT_DIR}
        RUNTIME_OUTPUT_DIRECTORY_DEBUG 			${FALCON_ENGINE_RUNTIME_OUTPUT_DIR}/Debug
        RUNTIME_OUTPUT_DIRECTORY_RELEASE        ${FALCON_ENGINE_RUNTIME_OUTPUT_DIR}/Release
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${FALCON_ENGINE_RUNTIME_OUTPUT_DIR}/Release
        RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL     ${FALCON_ENGINE_RUNTIME_OUTPUT_DIR}/Release

        DEBUG_POSTFIX                           "d"
        OUTPUT_NAME                             "${CURRENT_TARGET_NAME}${FALCON_ENGINE_OUTPUT_SUFFIX}"
    )
endfunction()

function(fe_set_target_folder CURRENT_TARGET_NAME CURRENT_FOLDER_NAME)

    set_target_properties(${CURRENT_TARGET_NAME} PROPERTIES
        FOLDER "${CURRENT_FOLDER_NAME}")

endfunction()

function(fe_set_target_language CURRENT_TARGET_NAME CURRENT_LANGUAGE_NAME)

    set_target_properties(${CURRENT_TARGET_NAME} PROPERTIES
        LINKER_LANGUAGE ${CURRENT_LANGUAGE_NAME})

endfunction()
